<a href="https://colab.research.google.com/github/Wrietenea/py_ml_lin_log_reg/blob/main/mlitmoreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
import numpy as np

In [ ]:
DATA = pd.read_csv("data4.csv", delimiter=',', index_col='id')
train_data=DATA
X = pd.DataFrame(train_data.drop(['Y'], axis=1))
Y = pd.DataFrame(train_data['Y'])
reg = LinearRegression().fit(X, Y)
print(DATA.mean())
print('theta1=', reg.coef_)
print('theta0=', reg.intercept_)
print('R^2=',reg.score(X, Y))

FileNotFoundError: ignored

In [ ]:
DATA = pd.read_csv("https://courses.openedu.ru/assets/courseware/v1/a11f0b9cb0074fdacc112eee71eb0b67/asset-v1:ITMOUniversity+BIGDATAINTROML+fall_2022_ITMO+type@asset+block/candy-data.csv", delimiter=',', index_col='competitorname')

In [ ]:
DATA

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                              
100 Grand                      1       0        1               0       0   
3 Musketeers                   1       0        0               0       1   
One dime                       0       0        0               0       0   
One quarter                    0       0        0               0       0   
Air Heads                      0       1        0               0       0   
...                          ...     ...      ...             ...     ...   
Snickers Crisper               1       0        1               1       0   
Sour Patch Kids                0       1        0               0       0   
Sour Patch Tricksters          0       1        0               0       0   
Starburst                      0       1        0               0       0   
Strawberry bon bons            0       1        0               0       0   

                       crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                               
100 Grand                             1     0    1         0         0.732   
3 Musketeers                          0     0    1         0         0.604   
One dime                              0     0    0         0         0.011   
One quarter                           0     0    0         0         0.011   
Air Heads                             0     0    0         0         0.906   
...                                 ...   ...  ...       ...           ...   
Snickers Crisper                      1     0    1         0         0.604   
Sour Patch Kids                       0     0    0         1         0.069   
Sour Patch Tricksters                 0     0    0         1         0.069   
Starburst                             0     0    0         1         0.151   
Strawberry bon bons                   0     1    0         1         0.569   

                       pricepercent  winpercent  Y  
competitorname                                      
100 Grand                     0.860   66.971725  1  
3 Musketeers                  0.511   67.602936  1  
One dime                      0.116   32.261086  0  
One quarter                   0.511   46.116505  0  
Air Heads                     0.511   52.341465  1  
...                             ...         ... ..  
Snickers Crisper              0.651   59.529251  1  
Sour Patch Kids               0.116   59.863998  1  
Sour Patch Tricksters         0.116   52.825947  1  
Starburst                     0.220   67.037628  1  
Strawberry bon bons           0.058   34.578991  0  

[70 rows x 13 columns]

In [ ]:
train_data = DATA.drop(['Runts','Starburst'])

In [ ]:
X = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))

In [ ]:
y = pd.DataFrame(train_data['winpercent'])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg = LinearRegression().fit(X, y)

In [ ]:
Runts = DATA.loc['Runts',:].to_frame().T
reg.predict(Runts.drop(['winpercent', 'Y'], axis=1))

array([[43.22457296]])

In [ ]:
Starburst = DATA.loc['Starburst',:].to_frame().T
reg.predict(Starburst.drop(['winpercent', 'Y'], axis=1))

array([[41.3443621]])

In [ ]:
reg.predict([[1, 1, 1, 1, 0, 1, 0, 1, 1, 0.91, 0.751]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[81.88984516]])

In [ ]:
DATA = pd.read_csv("https://courses.openedu.ru/assets/courseware/v1/a11f0b9cb0074fdacc112eee71eb0b67/asset-v1:ITMOUniversity+BIGDATAINTROML+fall_2022_ITMO+type@asset+block/candy-data.csv", delimiter=',', index_col='competitorname')
train_data=DATA.drop(['Nestle Crunch','Skittles wildberry','Sour Patch Tricksters'])
X = pd.DataFrame(train_data.drop(['winpercent','Y'], axis=1))
y = pd.DataFrame(train_data['Y'])

In [ ]:
reg = LogisticRegression(random_state = 2019, solver = 'lbfgs').fit(X, y.values.ravel())

In [ ]:
X

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                            
100 Grand                    1       0        1               0       0   
3 Musketeers                 1       0        0               0       1   
One dime                     0       0        0               0       0   
One quarter                  0       0        0               0       0   
Air Heads                    0       1        0               0       0   
...                        ...     ...      ...             ...     ...   
Snickers                     1       0        1               1       1   
Snickers Crisper             1       0        1               1       0   
Sour Patch Kids              0       1        0               0       0   
Starburst                    0       1        0               0       0   
Strawberry bon bons          0       1        0               0       0   

                     crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                             
100 Grand                           1     0    1         0         0.732   
3 Musketeers                        0     0    1         0         0.604   
One dime                            0     0    0         0         0.011   
One quarter                         0     0    0         0         0.011   
Air Heads                           0     0    0         0         0.906   
...                               ...   ...  ...       ...           ...   
Snickers                            0     0    1         0         0.546   
Snickers Crisper                    1     0    1         0         0.604   
Sour Patch Kids                     0     0    0         1         0.069   
Starburst                           0     0    0         1         0.151   
Strawberry bon bons                 0     1    0         1         0.569   

                     pricepercent  
competitorname                     
100 Grand                   0.860  
3 Musketeers                0.511  
One dime                    0.116  
One quarter                 0.511  
Air Heads                   0.511  
...                           ...  
Snickers                    0.651  
Snickers Crisper            0.651  
Sour Patch Kids             0.116  
Starburst                   0.220  
Strawberry bon bons         0.058  

[67 rows x 11 columns]

In [ ]:
test_data = pd.read_csv('https://courses.openedu.ru/assets/courseware/v1/d53b0f8b959d03cc84a992f6070cabc6/asset-v1:ITMOUniversity+BIGDATAINTROML+fall_2022_ITMO+type@asset+block/candy-test.csv',delimiter=',', index_col='competitorname')

In [ ]:
X_test = pd.DataFrame(test_data.drop(['Y'], axis=1))
Y_pred = reg.predict(X_test)

In [ ]:
Y_true = (test_data['Y'].to_frame().T).values.ravel()

In [ ]:
from sklearn import metrics

In [ ]:
fpr, tpr, thresholds = metrics.roc_curve(Y_true, Y_pred)
metrics.auc(fpr, tpr)

0.6499999999999999

In [ ]:
prob_test = reg.predict_proba(X_test)
prob_test = prob_test[:,1]

In [ ]:
prob_test

array([0.27311669, 0.38393711, 0.29659111, 0.3357791 , 0.7520206 ,
       0.68409012, 0.63071511, 0.76212973, 0.29167789, 0.38343972,
       0.3037946 , 0.13526518, 0.29247039, 0.58862556, 0.73170134])

In [ ]:
Y_pred

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
Y_true

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [ ]:
fpr, tpr, thresholds = metrics.roc_curve(Y_true, prob_test)
metrics.auc(fpr, tpr)

0.84

In [ ]:
tpr

array([0. , 0.6, 1. ])

In [ ]:
metrics.recall_score(Y_true, Y_pred)

0.6

In [ ]:
metrics.precision_score(Y_true, Y_pred)

0.5

In [ ]:
с1 = test_data.loc['Trolli Sour Bites',:].to_frame().T
c1 = с1.drop(['Y'], axis=1)
#отбор данных для предикторов и предсказание
reg.predict(с1.drop(['Y'], axis=1))

array([0])

In [ ]:
reg.predict_proba(c1)

array([[0.70832211, 0.29167789]])

In [ ]:
с2 = test_data.loc['Twizzlers',:].to_frame().T
c2 = с2.drop(['Y'], axis=1)
reg.predict_proba(c2)

array([[0.6962054, 0.3037946]])